### ISSUE TITLE
Constant Failures

### ISSUE THREAD

**Issue by bassrock** [blackfireio/blackfire-cookbook#2]
Hi,

Not sure this is for the cookbook but still an issue with it non-theless.

I can not get a constant setup with Blackfire. Sometimes it works perfectly other times i get an error like this:

```
After this operation, 5368 kB of additional disk space will be used.
Err http://packages.blackfire.io/ubuntu/ any/main blackfire-agent amd64 0.24.0
404  Not Found
STDERR: E: Failed to fetch http://packages.blackfire.io/ubuntu/pool/any/main/b/blackfire-agent/blackfire-agent_0.24.0_amd64.deb  404  Not Found

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
---- End output of apt-get -q -y install blackfire-agent=0.24.0 ----
Ran apt-get -q -y install blackfire-agent=0.24.0 returned 100


Resource Declaration:
---------------------
# In /var/lib/aws/opsworks/cache.stage2/cookbooks/blackfire/recipes/agent.rb

15: package 'blackfire-agent' do
16:   version agent_version
17: end
18:



Compiled Resource:
------------------
# Declared in /var/lib/aws/opsworks/cache.stage2/cookbooks/blackfire/recipes/agent.rb:15:in `from_file'

package("blackfire-agent") do
action :install
retries 0
retry_delay 2
package_name "blackfire-agent"
version "0.24.0"
cookbook_name "blackfire"
recipe_name "agent"
end
```

It seems the package repo is never stable with the versioning of the agent.

**Comment by fabpot** [comment]
ping @tucksaun

**Comment by bassrock** [comment]
@tucksaun great to see a fix so quick!! Thanks!

**Comment by bassrock** [comment]
@fabpot shouldn't we wait to close it until a release or merge to the main repo?

**Comment by tucksaun** [comment]
@bassrock actually the linked commit is not a fix (even if related) :/
The true issue was on the releases API not up-to-date but it should be fixed by now.

**Comment by bassrock** [comment]
@tucksaun  looks like there is a regression of this happening, not sure if it is the cookbook or the repo not up to date, but my deploy gets stuck here:

```
[2016-02-05T20:06:17-07:00] INFO: Processing apt_package[blackfire-agent] action install (blackfire::agent line 15)

================================================================================
Error executing action `install` on resource 'apt_package[blackfire-agent]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '100'
---- Begin output of apt-get -q -y install blackfire-agent=1.4.4 ----
STDOUT: Reading package lists...
Building dependency tree...
Reading state information...
STDERR: E: Version '1.4.4' for 'blackfire-agent' was not found
---- End output of apt-get -q -y install blackfire-agent=1.4.4 ----
Ran apt-get -q -y install blackfire-agent=1.4.4 returned 100

Resource Declaration:
---------------------
# In /var/chef/runs/17d6645d-1111-44be-bfba-0dc7d3dbf556/local-mode-cache/cache/cookbooks/blackfire/recipes/agent.rb

15: package 'blackfire-agent' do
16:   version agent_version
17: end
18: 

Compiled Resource:
------------------
# Declared in /var/chef/runs/17d6645d-1111-44be-bfba-0dc7d3dbf556/local-mode-cache/cache/cookbooks/blackfire/recipes/agent.rb:15:in `from_file'

apt_package("blackfire-agent") do
action [:install]
retries 0
retry_delay 2
default_guard_interpreter :default
package_name "blackfire-agent"
version "1.4.4"
declared_type :package
cookbook_name "blackfire"
recipe_name "agent"
end

[2016-02-05T20:06:18-07:00] INFO: Running queued delayed notifications before re-raising exception
[2016-02-05T20:06:18-07:00] ERROR: Running exception handlers
[2016-02-05T20:06:18-07:00] ERROR: Exception handlers complete
[2016-02-05T20:06:18-07:00] FATAL: Stacktrace dumped to /var/chef/runs/17d6645d-1111-44be-bfba-0dc7d3dbf556/local-mode-cache/cache/chef-stacktrace.out
[2016-02-05T20:06:18-07:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-02-05T20:06:18-07:00] ERROR: apt_package[blackfire-agent] (blackfire::agent line 15) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100
```

**Comment by tucksaun** [comment]
Well, the latest version for `blackfire-agent` is definitely the 1.4.4 and it is available.
It seems your apt cache is not up to date but the cookbook is supposed to update the repository before updating the packages.
Could you check which versions of the package your apt currently knows (`sudo apt-cache madison blackfire-agent`)? And then check in the chef output if the `blackfire repository update` resource is properly executed?

**Comment by bassrock** [comment]
So the `apt-get update` is not running. I think it is because of https://github.com/blackfireio/blackfire-cookbook/blob/master/recipes/repository.rb#L32

This is on an upgrade of blackfire, ie. running the cookbook again after it had already installed blackfire before, and after there has been an update to blackfire.

**Comment by tucksaun** [comment]
Well actually this line is meant to call `apt-get update` on each run, the check is here to avoid unnecessary updates because adding a repo already trigger an initial update.
I will have a look ASAP.

**Comment by tucksaun** [comment]
@bassrock could you provide me a complete run log?
